language: node_js
node_js:
  - node

jobs:
  include:
    - stage: release
      node_js: node
      deploy:
        provider: script
        script:
          - yarn semantic-release

script:
  - yarn lint
  - yarn test
  - yarn build
